### ISSUE TITLE
[       script:FIREAC] FIREAC: Warning! Your fireac.json is missing, Regenerating your fireac.json file!

### ISSUE THREAD

**Issue by subhampro** [AmIrReZa386/FIREAC#3]
I get this error on console ~!!``` [       script:FIREAC] FIREAC: Warning! Your fireac.json is missing, Regenerating your fireac.json file!``` 
after this msg there is no firec.json file generated still !

**Comment by subhampro** [comment]
I can fix it a! give me push access !

**Comment by GoodLiferp22** [comment]
Hello bro, I have installed your anti cheat, it loads everything without error. Now, I have 3 problems, he constantly warns people for anti spawn ped, anti teleport and another person he threw anti godmode, On the other hand when I load the admin it detects them, but only 1 person gets the admin message and Allows you to open the menu. Sorry if I write to you here, it's because your discord invitation has expired and it's the only way I found to write. I wanted to see if it can be solved because the truth is that the anti cheat you created is very good. I await an answer. Greetings Matthias

**Comment by xxoptikxx** [comment]
Hello Guys,
i Like this AC its very Simple and Hard for Cheaters 
but...... its banned my friend an we dont can unban him what can i do?
` [ script:FIREAC] FIREAC: Warning! Your fireac.json is missing, Regenerating your fireac.json file!` and how can i get these?

sry for my bad english im from Germany

**Comment by AmIrReZa386** [comment]
Hi,

This is only warn, if you **delete or have problem** in `fireac.json`, anti cheat **recreate**(or format) file for you , this is not error thank's 🤞

**Comment by xxoptikxx** [comment]
the script have no `fireac.json` this is the problem

**Comment by xxoptikxx** [comment]
and your dc link is broke

**Comment by xxoptikxx** [comment]
and the script dont recreate the `fireac.json`

**Comment by AmIrReZa386** [comment]
okey i check it again and update my link

if any problem detected i update FIREAC

**Comment by AmIrReZa386** [comment]
I fix this problem @xxoptikxx & @subhampro 

if it's now fix report me again !
